--
-- PostgreSQL database dump
--

-- Dumped from database version 13.4
-- Dumped by pg_dump version 13.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: artifact; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.artifact (
    artifact_id integer NOT NULL,
    artifact_type smallint,
    bonus integer,
    "character" integer
);


ALTER TABLE public.artifact OWNER TO postgres;

--
-- Name: artifact_artifact_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.artifact ALTER COLUMN artifact_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.artifact_artifact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: character; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."character" (
    character_id integer NOT NULL,
    character_name text,
    character_level smallint,
    current_experience integer,
    hp integer,
    attack_strength integer,
    defence_strength integer,
    hero_class smallint
);


ALTER TABLE public."character" OWNER TO postgres;

--
-- Name: character_character_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."character" ALTER COLUMN character_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.character_character_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: artifact; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.artifact (artifact_id, artifact_type, bonus, "character") FROM stdin;
3	\N	0	\N
5	\N	0	\N
7	\N	0	\N
10	\N	0	\N
11	1	4	20
12	\N	0	\N
14	0	8	20
15	2	8	20
16	1	3	18
17	0	1	18
18	1	6	19
19	0	8	19
20	2	5	19
\.


--
-- Data for Name: character; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."character" (character_id, character_name, character_level, current_experience, hp, attack_strength, defence_strength, hero_class) FROM stdin;
17	adventurer	1	0	10	5	5	0
20	enshertid	4	1750	33	17	17	0
18	enshertid	2	500	13	7	7	0
19	enshertid	4	250	25	11	11	0
\.


--
-- Name: artifact_artifact_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.artifact_artifact_id_seq', 20, true);


--
-- Name: character_character_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.character_character_id_seq', 20, true);


--
-- Name: artifact artifact_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.artifact
    ADD CONSTRAINT artifact_pkey PRIMARY KEY (artifact_id);


--
-- Name: character character_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."character"
    ADD CONSTRAINT character_pkey PRIMARY KEY (character_id);


--
-- Name: artifact fk_artifact__character; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.artifact
    ADD CONSTRAINT fk_artifact__character FOREIGN KEY ("character") REFERENCES public."character"(character_id);


--
-- PostgreSQL database dump complete
--

